#ifndef VALIDACAOCAMPOSESPERADOSSEMIGLOBE_H
#define VALIDACAOCAMPOSESPERADOSSEMIGLOBE_H


class ValidacaoCamposEsperadosSEMIGLOBE
{
public:
    ValidacaoCamposEsperadosSEMIGLOBE();
};

#endif // VALIDACAOCAMPOSESPERADOSSEMIGLOBE_H